# Generated by Django 3.1.7 on 2021-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210228_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='details',
            field=models.TextField(),
        ),
    ]
