# Generated by Django 3.1.7 on 2021-02-28 11:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210228_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadingmodal',
            name='html',
            field=tinymce.models.HTMLField(),
        ),
    ]
