# Generated by Django 3.1.7 on 2021-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210228_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='heading',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='loadingmodal',
            name='html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newpage',
            name='heading',
            field=models.CharField(max_length=1024),
        ),
    ]
