# Generated by Django 3.1.7 on 2021-02-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210228_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpage',
            name='url',
            field=models.CharField(default='', help_text='aryaSamaj.com/{YOUR INPUT}/', max_length=1024),
            preserve_default=False,
        ),
    ]
