# Generated by Django 3.1.7 on 2021-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210228_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincontrols',
            name='homePageText',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
