# Generated by Django 3.1.7 on 2021-03-04 09:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_carouselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='details',
            field=tinymce.models.HTMLField(blank=True, default='.'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
